name: Docker Android CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.gpu'
      - '.github/workflows/*'
      - 'deps/*'
      - 'keys/*'
      - 'scripts/*'

jobs:

  # Builds all Android API images with API level 33 and below.
  build-apis:
    strategy:
      matrix:
        version: [33, 32, 31, 30, 29, 28]
        image: [
          { name: 'google_apis', suffix: '' },
          { name: 'google_apis_playstore', suffix: '-playstore' }
        ]
        gpu: [
          { file: 'Dockerfile', suffix: '' },
          { file: 'Dockerfile.gpu', suffix: '-cuda' }
        ]
        # 由于目前docker配置过程中,仍然需要下载adb, 下载连接写死了, 暂时只支持x86, 所以暂不适配amd64/arm64
        #architecture: [amd64, arm64]
        architecture: [x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      #
      # # 启用 Buildx，支持多架构构建 for arm64 and amd64
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2  
      # #
      - name: Build Docker image api-${{ matrix.version }}${{ matrix.image.suffix }}
        # 在 arm64 架构时排除 CUDA 配置
        if: ${{ matrix.architecture == 'x86_64' || matrix.architecture == 'amd64' || (matrix.architecture == 'arm64' && matrix.gpu.suffix == '') }}
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ${{ matrix.gpu.file }}
          tags: cndaqiang/docker-android-emulator:api-${{ matrix.version }}${{ matrix.image.suffix }}${{ matrix.architecture }}${{ matrix.gpu.suffix }}
          build-args: |
            API_LEVEL=${{ matrix.version }}
            IMG_TYPE=${{ matrix.image.name }}
            ARCHITECTURE=${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}
  # Builds a minimal image without any Android SDK images.
  build-minimal:
    strategy:
      matrix:
        gpu: [
          { file: 'Dockerfile', suffix: '' },
          { file: 'Dockerfile.gpu', suffix: '-cuda' }
        ]
        architecture: [x86_64]
        #architecture: [amd64, arm64] 
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      #
      # # 启用 Buildx，支持多架构构建 for arm64 and amd64
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2  
      # #
      - name: Build minimal Docker image
        # 在 arm64 架构时排除 CUDA 配置
        if: ${{ matrix.architecture == 'x86_64' || matrix.architecture == 'amd64' || (matrix.architecture == 'arm64' && matrix.gpu.suffix == '') }}
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ${{ matrix.gpu.file }}
          tags: cndaqiang/docker-android-emulator:minimal${{ matrix.architecture }}${{ matrix.gpu.suffix }}
          build-args: INSTALL_ANDROID_SDK=0
          platforms: linux/${{ matrix.architecture }}

